/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedHierarchyRouteImport } from './routes/_authed/hierarchy'
import { Route as AuthedReviewQueueRouteImport } from './routes/_authed/review-queue'
import { Route as AuthedAreasIndexRouteImport } from './routes/_authed/areas/index'
import { Route as AuthedAreasAreaGroupRouteImport } from './routes/_authed/areas/$areaGroup'
import { Route as AuthedMembersIndexRouteImport } from './routes/_authed/members/index'
import { Route as AuthedMembersMemberIdRouteImport } from './routes/_authed/members/$memberId'
import { Route as AuthedStagingNeedsReviewRouteImport } from './routes/_authed/staging/needs-review'
import { Route as AuthedStagingRemovalRequestsRouteImport } from './routes/_authed/staging/removal-requests'
import { Route as AuthedStagingUnassignedRouteImport } from './routes/_authed/staging/unassigned'
import { Route as AuthedUsersIndexRouteImport } from './routes/_authed/users/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiWebhooksGoogleFormsMemberIntakeRouteImport } from './routes/api/webhooks/google-forms/member-intake'
import { Route as ApiWebhooksGoogleFormsMemberRemovalRouteImport } from './routes/api/webhooks/google-forms/member-removal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHierarchyRoute = AuthedHierarchyRouteImport.update({
  id: '/hierarchy',
  path: '/hierarchy',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReviewQueueRoute = AuthedReviewQueueRouteImport.update({
  id: '/review-queue',
  path: '/review-queue',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAreasIndexRoute = AuthedAreasIndexRouteImport.update({
  id: '/areas/',
  path: '/areas/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAreasAreaGroupRoute = AuthedAreasAreaGroupRouteImport.update({
  id: '/areas/$areaGroup',
  path: '/areas/$areaGroup',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMembersIndexRoute = AuthedMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMembersMemberIdRoute = AuthedMembersMemberIdRouteImport.update({
  id: '/members/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStagingNeedsReviewRoute =
  AuthedStagingNeedsReviewRouteImport.update({
    id: '/staging/needs-review',
    path: '/staging/needs-review',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedStagingRemovalRequestsRoute =
  AuthedStagingRemovalRequestsRouteImport.update({
    id: '/staging/removal-requests',
    path: '/staging/removal-requests',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedStagingUnassignedRoute = AuthedStagingUnassignedRouteImport.update({
  id: '/staging/unassigned',
  path: '/staging/unassigned',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersIndexRoute = AuthedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksGoogleFormsMemberIntakeRoute =
  ApiWebhooksGoogleFormsMemberIntakeRouteImport.update({
    id: '/api/webhooks/google-forms/member-intake',
    path: '/api/webhooks/google-forms/member-intake',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksGoogleFormsMemberRemovalRoute =
  ApiWebhooksGoogleFormsMemberRemovalRouteImport.update({
    id: '/api/webhooks/google-forms/member-removal',
    path: '/api/webhooks/google-forms/member-removal',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/hierarchy': typeof AuthedHierarchyRoute
  '/review-queue': typeof AuthedReviewQueueRoute
  '/areas/$areaGroup': typeof AuthedAreasAreaGroupRoute
  '/members/$memberId': typeof AuthedMembersMemberIdRoute
  '/staging/needs-review': typeof AuthedStagingNeedsReviewRoute
  '/staging/removal-requests': typeof AuthedStagingRemovalRequestsRoute
  '/staging/unassigned': typeof AuthedStagingUnassignedRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/areas/': typeof AuthedAreasIndexRoute
  '/members/': typeof AuthedMembersIndexRoute
  '/users/': typeof AuthedUsersIndexRoute
  '/api/webhooks/google-forms/member-intake': typeof ApiWebhooksGoogleFormsMemberIntakeRoute
  '/api/webhooks/google-forms/member-removal': typeof ApiWebhooksGoogleFormsMemberRemovalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/hierarchy': typeof AuthedHierarchyRoute
  '/review-queue': typeof AuthedReviewQueueRoute
  '/areas/$areaGroup': typeof AuthedAreasAreaGroupRoute
  '/members/$memberId': typeof AuthedMembersMemberIdRoute
  '/staging/needs-review': typeof AuthedStagingNeedsReviewRoute
  '/staging/removal-requests': typeof AuthedStagingRemovalRequestsRoute
  '/staging/unassigned': typeof AuthedStagingUnassignedRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/areas': typeof AuthedAreasIndexRoute
  '/members': typeof AuthedMembersIndexRoute
  '/users': typeof AuthedUsersIndexRoute
  '/api/webhooks/google-forms/member-intake': typeof ApiWebhooksGoogleFormsMemberIntakeRoute
  '/api/webhooks/google-forms/member-removal': typeof ApiWebhooksGoogleFormsMemberRemovalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/hierarchy': typeof AuthedHierarchyRoute
  '/_authed/review-queue': typeof AuthedReviewQueueRoute
  '/_authed/areas/$areaGroup': typeof AuthedAreasAreaGroupRoute
  '/_authed/members/$memberId': typeof AuthedMembersMemberIdRoute
  '/_authed/staging/needs-review': typeof AuthedStagingNeedsReviewRoute
  '/_authed/staging/removal-requests': typeof AuthedStagingRemovalRequestsRoute
  '/_authed/staging/unassigned': typeof AuthedStagingUnassignedRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/areas/': typeof AuthedAreasIndexRoute
  '/_authed/members/': typeof AuthedMembersIndexRoute
  '/_authed/users/': typeof AuthedUsersIndexRoute
  '/api/webhooks/google-forms/member-intake': typeof ApiWebhooksGoogleFormsMemberIntakeRoute
  '/api/webhooks/google-forms/member-removal': typeof ApiWebhooksGoogleFormsMemberRemovalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/hierarchy'
    | '/review-queue'
    | '/areas/$areaGroup'
    | '/members/$memberId'
    | '/staging/needs-review'
    | '/staging/removal-requests'
    | '/staging/unassigned'
    | '/api/auth/$'
    | '/areas/'
    | '/members/'
    | '/users/'
    | '/api/webhooks/google-forms/member-intake'
    | '/api/webhooks/google-forms/member-removal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/hierarchy'
    | '/review-queue'
    | '/areas/$areaGroup'
    | '/members/$memberId'
    | '/staging/needs-review'
    | '/staging/removal-requests'
    | '/staging/unassigned'
    | '/api/auth/$'
    | '/areas'
    | '/members'
    | '/users'
    | '/api/webhooks/google-forms/member-intake'
    | '/api/webhooks/google-forms/member-removal'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/dashboard'
    | '/_authed/hierarchy'
    | '/_authed/review-queue'
    | '/_authed/areas/$areaGroup'
    | '/_authed/members/$memberId'
    | '/_authed/staging/needs-review'
    | '/_authed/staging/removal-requests'
    | '/_authed/staging/unassigned'
    | '/api/auth/$'
    | '/_authed/areas/'
    | '/_authed/members/'
    | '/_authed/users/'
    | '/api/webhooks/google-forms/member-intake'
    | '/api/webhooks/google-forms/member-removal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhooksGoogleFormsMemberIntakeRoute: typeof ApiWebhooksGoogleFormsMemberIntakeRoute
  ApiWebhooksGoogleFormsMemberRemovalRoute: typeof ApiWebhooksGoogleFormsMemberRemovalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/hierarchy': {
      id: '/_authed/hierarchy'
      path: '/hierarchy'
      fullPath: '/hierarchy'
      preLoaderRoute: typeof AuthedHierarchyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/review-queue': {
      id: '/_authed/review-queue'
      path: '/review-queue'
      fullPath: '/review-queue'
      preLoaderRoute: typeof AuthedReviewQueueRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/areas/': {
      id: '/_authed/areas/'
      path: '/areas'
      fullPath: '/areas/'
      preLoaderRoute: typeof AuthedAreasIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/areas/$areaGroup': {
      id: '/_authed/areas/$areaGroup'
      path: '/areas/$areaGroup'
      fullPath: '/areas/$areaGroup'
      preLoaderRoute: typeof AuthedAreasAreaGroupRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/members/': {
      id: '/_authed/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthedMembersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/members/$memberId': {
      id: '/_authed/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof AuthedMembersMemberIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/staging/needs-review': {
      id: '/_authed/staging/needs-review'
      path: '/staging/needs-review'
      fullPath: '/staging/needs-review'
      preLoaderRoute: typeof AuthedStagingNeedsReviewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/staging/removal-requests': {
      id: '/_authed/staging/removal-requests'
      path: '/staging/removal-requests'
      fullPath: '/staging/removal-requests'
      preLoaderRoute: typeof AuthedStagingRemovalRequestsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/staging/unassigned': {
      id: '/_authed/staging/unassigned'
      path: '/staging/unassigned'
      fullPath: '/staging/unassigned'
      preLoaderRoute: typeof AuthedStagingUnassignedRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/users/': {
      id: '/_authed/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthedUsersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/google-forms/member-intake': {
      id: '/api/webhooks/google-forms/member-intake'
      path: '/api/webhooks/google-forms/member-intake'
      fullPath: '/api/webhooks/google-forms/member-intake'
      preLoaderRoute: typeof ApiWebhooksGoogleFormsMemberIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/google-forms/member-removal': {
      id: '/api/webhooks/google-forms/member-removal'
      path: '/api/webhooks/google-forms/member-removal'
      fullPath: '/api/webhooks/google-forms/member-removal'
      preLoaderRoute: typeof ApiWebhooksGoogleFormsMemberRemovalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedHierarchyRoute: typeof AuthedHierarchyRoute
  AuthedReviewQueueRoute: typeof AuthedReviewQueueRoute
  AuthedAreasAreaGroupRoute: typeof AuthedAreasAreaGroupRoute
  AuthedMembersMemberIdRoute: typeof AuthedMembersMemberIdRoute
  AuthedStagingNeedsReviewRoute: typeof AuthedStagingNeedsReviewRoute
  AuthedStagingRemovalRequestsRoute: typeof AuthedStagingRemovalRequestsRoute
  AuthedStagingUnassignedRoute: typeof AuthedStagingUnassignedRoute
  AuthedAreasIndexRoute: typeof AuthedAreasIndexRoute
  AuthedMembersIndexRoute: typeof AuthedMembersIndexRoute
  AuthedUsersIndexRoute: typeof AuthedUsersIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedHierarchyRoute: AuthedHierarchyRoute,
  AuthedReviewQueueRoute: AuthedReviewQueueRoute,
  AuthedAreasAreaGroupRoute: AuthedAreasAreaGroupRoute,
  AuthedMembersMemberIdRoute: AuthedMembersMemberIdRoute,
  AuthedStagingNeedsReviewRoute: AuthedStagingNeedsReviewRoute,
  AuthedStagingRemovalRequestsRoute: AuthedStagingRemovalRequestsRoute,
  AuthedStagingUnassignedRoute: AuthedStagingUnassignedRoute,
  AuthedAreasIndexRoute: AuthedAreasIndexRoute,
  AuthedMembersIndexRoute: AuthedMembersIndexRoute,
  AuthedUsersIndexRoute: AuthedUsersIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksGoogleFormsMemberIntakeRoute:
    ApiWebhooksGoogleFormsMemberIntakeRoute,
  ApiWebhooksGoogleFormsMemberRemovalRoute:
    ApiWebhooksGoogleFormsMemberRemovalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
